version: "3.9"

services:
  db:
    image: docker.io/library/postgres:15
    container_name: db_dev
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    networks:
      - mi_red_dev
    ports:
      - "5432:5432"

  web:
    build: .
    container_name: web_dev
    restart: always
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      DEBUG: "True"
      PYTHONUNBUFFERED: "1"
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DJANGO_DEBUG: ${DJANGO_DEBUG}
    volumes:
      - .:/app
    networks:
      - mi_red_dev
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend_dev
    restart: always
    depends_on:
      - web
    ports:
      - "3000:3000"
    environment:
      VITE_API_URL: ${VITE_API_URL}
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - mi_red_dev

  frontend-public:
    build:
      context: ./frontend-public
      dockerfile: Dockerfile
    container_name: frontend-public_dev
    restart: always
    depends_on:
      - web
    ports:
      - "3001:3001"
    environment:
      VITE_API_URL: ${VITE_API_URL}
    volumes:
      - ./frontend-public:/app
      - /app/node_modules
    networks:
      - mi_red_dev

volumes:
  postgres_data_dev:

networks:
  mi_red_dev:
