 
version: "3.9"

services:
  # db:
  #   image: docker.io/library/postgres:15
  #   container_name: db
  #   restart: always
  #   environment:
  #     POSTGRES_DB: ${POSTGRES_DB}
  #     POSTGRES_USER: ${POSTGRES_USER}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   networks:
  #     - mi_red

  web:
    build: .
    container_name: web
    restart: always
    environment:
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DJANGO_DEBUG: ${DJANGO_DEBUG}
    ports:
      - "8000:8000"
    networks:
      - mi_red
      - postgres_global_network 

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    restart: always
    depends_on:
      - web
    ports:
      - "3000:3000"
    networks:
      - mi_red

  frontend-public:
    build:
      context: ./frontend-public
      dockerfile: Dockerfile
    container_name: frontend-public
    restart: always
    depends_on:
      - web
    ports:
      - "3001:3001"
    networks:
      - mi_red

networks:
  mi_red:
  postgres_global_network:
    external: true  # Usa la red externa existente